version: "3"
services:
  go:
    build: 
      dockerfile: ./api/Dockerfile
    container_name: go-api
    tty: true
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - ./api:/api
    networks:
      - app-net

  db:
    image: mysql:5.7
    container_name: db
    platform: linux/amd64
    hostname: mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 13306:3306
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
